### ISSUE TITLE
loadURDF doesn't load obj files correctly

### ISSUE THREAD

**Issue by ElectronicElephant** [mvig-robotflow/pyrfuniverse#4]
## Environment
It happens in any version of RFU.

## Steps to reproduce

1. Download the zip file [01b24b02-0e4e-11ed-81d4-ec2e98c7e246.zip](https://github.com/mvig-robotflow/pyrfuniverse/files/11541382/01b24b02-0e4e-11ed-81d4-ec2e98c7e246.zip)
2. Use `loadURDF` function to load it into RFU
3. The mesh is broken
![image](https://github.com/mvig-robotflow/pyrfuniverse/assets/20351686/2d853418-4fb3-4754-b157-fd4500a400d9)

## Expected Behaviour

1. Use URDF-Importer extension to load it directly into unity
![image](https://github.com/mvig-robotflow/pyrfuniverse/assets/20351686/ca27fb16-602a-4210-b683-4fcfbb412c2d)

2. In PyBullet,
![image](https://github.com/mvig-robotflow/pyrfuniverse/assets/20351686/a4dc848a-63a2-4b3f-84d6-dc2a007b6228)

**Comment by ghzh26252** [comment]
`LoadURDF` uses [URDF-Importer's runtime module](https://github.com/Unity-Technologies/URDF-Importer/tree/main/com.unity.robotics.urdf-importer/Runtime), which uses another repo: [UnityMeshImporter](https://github.com/eastskykang/UnityMeshImporter). 
The module defaults to using 16-bit vertex IndexFormat when importing meshes,
so an exception will occurs when importing meshes with more than 65536 vertices.

The following code has been added to fix this issue: 
`uMesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;`
This fix will be included in the next release.
